name: Release DDNS Scripts

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release DDNS Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ADGUARDPRIVATE_DDNS_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Unix script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ADGUARDPRIVATE_DDNS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: unix/ddns.sh
          asset_name: ddns.sh
          asset_content_type: application/x-sh

      - name: Upload Windows script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ADGUARDPRIVATE_DDNS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: win/ddns.ps1
          asset_name: ddns.ps1
          asset_content_type: text/plain